#!/bin/sh

. /usr/share/libubox/jshn.sh

status() {
	/usr/bin/soya-asn-router status
}

interfaces() {
	/usr/bin/soya-asn-router interfaces
}

apply_routes() {
	/usr/bin/soya-asn-router apply-routes
}

preview_routes() {
	/usr/bin/soya-asn-router preview-routes
}

pause_routes() {
	/usr/bin/soya-asn-router pause-routes
}

resume_routes() {
	/usr/bin/soya-asn-router resume-routes
}

dedupe_config() {
	/usr/bin/soya-asn-router dedupe-config
}

import_url() {
	local input="$1"
	local url interface

	[ -n "$input" ] || read input
	json_load "${input:-{}}"
	json_get_var url url
	json_get_var interface interface

	/usr/bin/soya-asn-router import-url "$url" "$interface"
}

bulk_delete() {
	local input="$1"
	local asns

	[ -n "$input" ] || read input
	json_load "${input:-{}}"
	json_get_var asns asns

	/usr/bin/soya-asn-router bulk-delete "$asns"
}

bulk_set_interface() {
	local input="$1"
	local asns interface

	[ -n "$input" ] || read input
	json_load "${input:-{}}"
	json_get_var asns asns
	json_get_var interface interface

	/usr/bin/soya-asn-router bulk-set-interface "$asns" "$interface"
}

start_sync() {
	/usr/bin/soya-asn-router "$1" >/dev/null 2>&1 &

	json_init
	json_add_boolean started 1
	json_dump
}

list_methods() {
	json_init
	json_add_object status
	json_close_object
	json_add_object interfaces
	json_close_object
	json_add_object sync_missing
	json_close_object
	json_add_object sync_all
	json_close_object
	json_add_object apply_routes
	json_close_object
	json_add_object preview_routes
	json_close_object
	json_add_object pause_routes
	json_close_object
	json_add_object resume_routes
	json_close_object
	json_add_object dedupe_config
	json_close_object
	json_add_object import_url
	json_add_string url "string"
	json_add_string interface "string"
	json_close_object
	json_add_object bulk_delete
	json_add_string asns "string"
	json_close_object
	json_add_object bulk_set_interface
	json_add_string asns "string"
	json_add_string interface "string"
	json_close_object
	json_dump
}

case "$1" in
	list)
		list_methods
		;;
	call)
		case "$2" in
			status)
				status
				;;
			interfaces)
				interfaces
				;;
			sync_missing)
				start_sync sync-missing
				;;
			sync_all)
				start_sync sync-all
				;;
			apply_routes)
				apply_routes
				;;
			preview_routes)
				preview_routes
				;;
			pause_routes)
				pause_routes
				;;
			resume_routes)
				resume_routes
				;;
			dedupe_config)
				dedupe_config
				;;
			import_url)
				import_url "$3"
				;;
			bulk_delete)
				bulk_delete "$3"
				;;
			bulk_set_interface)
				bulk_set_interface "$3"
				;;
		esac
		;;
esac
